
# Docker Compose: Render, doğrudan docker-compose.yml dosyasını desteklemez. Bunun yerine,
# render.yaml dosyası ile servislerinizi tanımlamanız gerekir.

services:
  # Web uygulaması
  - type: web
    name: ecommerce-app
    env: docker
    plan: free
    repo: https://github.com/GORKEMDEMIRKIRAN/ECommerceWebApp.git # GitHub repo URL'nizi buraya yazın
    branch: main # Ana branch'inizi belirtin
    dockerfilePath: ./Dockerfile # Dockerfile'ın yolu
    dockerContext: . # Docker build context
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__PostgreSqlConnection
        fromService:
          type: postgres
          name: ecommerce-db
          property: connectionString
    healthCheckPath: /health # Sağlık kontrolü için endpoint (uygulamanızda varsa)

databases:
  # PostgreSQL veritabanı
  - name: ecommerce-db
    plan: free
    type: postgres
    version: "15" # PostgreSQL sürümü (Render'ın desteklediği en son sürümü kullanabilirsiniz)
    ipAllowList: [] # Tüm IP'lere izin ver (boş bırakırsanız)
